### PR TITLE
Start of hunting about missing g_object_unref()

### PR DESCRIPTION
**Pull request by jjceresa**
`SwamiControl `objects and friends are particularly sensible leading into frequent memory leak due to missing call to **g_object_unref()** when the application exit.
This PR provide a debugging capture API in `libswami-util.c` that should help to catch missing **g_object_unref** in next commits comming soon.

### CODE REVIEW

**Comment by derselbst** [comment]
I would prefer it if you could keep this on a separate branch for the time being rather than merging to master. Because if I want to release a new version of Swami I would like to avoid having this debug code around.

**Comment by jjceresa** [comment]
Yes, of course. Please keep this PR opened the necessary time. I will provide next commit.

**Comment by jjceresa** [comment]
PR https://github.com/swami/swami/pull/31 is the result of branch `gobject-leak `but without the debugging code. We can close the current PR that is useless. However may be the branch **gobject-leak** could be useful sooner or later ?.

**Comment by derselbst** [comment]
Sure, I'll keep the branch.

**Pull request closed without merging**
