### PR TITLE
Ensure correct gobject property name

### PR DESCRIPTION
**Pull request by jjceresa**
This addresses issue https://github.com/swami/swami/issues/61.

When registering gobject's property from fluidsynth settings, we must ensure that the property name doesn't contain a dot.
Dot character '.' are explicitly replaced by '-'.

### CODE REVIEW

**Comment by derselbst** [comment]
Most of the changes you want to merge here already exist in master. The libinstpatch version 1.1.6 is also correct. Just keep it that way, I'll cherry-pick the relevant changes on the weekend.

**Comment by jjceresa** [comment]
>The libinstpatch version 1.1.6 is also correct.

Ok.

**Comment by jjceresa** [comment]
>The libinstpatch version 1.1.6 is also correct.

I changed this because libinstpatch 1.1.6 doesn't yet exist. Only 1.1.5 exists.

**Comment by derselbst** [comment]
> I changed this because libinstpatch 1.1.6 doesn't yet exist. Only 1.1.5 exists.

Yes, but we need 1.1.6 because of the SLI getter functions.

**Comment by jjceresa** [comment]
>Most of the changes you want to merge here already exist in master.

Yes, I just realized this too later because my local master branch wasn't up to date.
However, notice that the change done in `ef857ea` fix also a bit more correct variable name `prop_name` than on actual master.
Also it worth to add `264b50f`.

**Pull request closed without merging**
